version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: minitest
    versions:
    - 5.14.3
    - 5.14.4
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: capybara
    versions:
    - 3.35.1
    - 3.35.3
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: web-console
    versions:
    - 4.1.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
