version: '3.8'

volumes:
  postgres:
    driver: local
  assets:
    driver: local


services:
  postgres:
    restart: always
    image: postgres:9.6-alpine
    env_file: .env_deployment

  web:
    restart: always
    image: familyfavourites:deploy
    build: .
    volumes:
      - assets:/app/public/assets/
    command: bundle exec puma -e production
    env_file: .env_deployment
    depends_on:
      - postgres

  nginx:
    restart: always
    image: nginx
    depends_on:
      - web
    env_file: .env_deployment
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - assets:/app/public/assets/
    ports:
      - "80:80"
